# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-cloud-dns
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: Terraform Google Cloud DNS Module
    source:
      repo: https://github.com/terraform-google-modules/terraform-google-cloud-dns.git
      sourceType: git
    version: 6.1.0
    actuationTool:
      flavor: Terraform
      version: ">= 1.3"
    description: {}
  content:
    subBlueprints:
      - name: dns_response_policy
        location: modules/dns_response_policy
    examples:
      - name: dns_response_policy
        location: examples/dns_response_policy
      - name: forwarding-zone
        location: examples/forwarding-zone
      - name: peering-zone
        location: examples/peering-zone
      - name: private-zone
        location: examples/private-zone
      - name: public-zone
        location: examples/public-zone
  interfaces:
    variables:
      - name: domain
        description: Zone domain, must end with a period.
        varType: string
        required: true
      - name: name
        description: Zone name, must be unique within the project.
        varType: string
        required: true
      - name: private_visibility_config_networks
        description: List of VPC self links that can see this zone.
        varType: list(string)
        defaultValue: []
      - name: gke_clusters_list
        description: The list of Google Kubernetes Engine clusters that can see this zone.
        varType: list(string)
        defaultValue: []
        connections:
          - source:
              source: github.com/terraform-google-modules/terraform-google-kubernetes-engine//modules/gke-standard-cluster
              version: ">=38.0.1"
            spec:
              outputExpr: cluster_id
      - name: project_id
        description: Project id for the zone.
        varType: string
        required: true
      - name: target_name_server_addresses
        description: List of target name servers for forwarding zone.
        varType: list(map(any))
        defaultValue: []
      - name: target_network
        description: Peering network.
        varType: string
        defaultValue: ""
      - name: description
        description: zone description (shown in console)
        varType: string
        defaultValue: Managed by Terraform
      - name: type
        description: Type of zone to create, valid values are 'public', 'private', 'forwarding', 'peering', 'reverse_lookup' and 'service_directory'.
        varType: string
        defaultValue: private
      - name: dnssec_config
        description: "Object containing : kind, non_existence, state. Please see https://www.terraform.io/docs/providers/google/r/dns_managed_zone#dnssec_config for futhers details"
        varType: any
        defaultValue: {}
      - name: labels
        description: A set of key/value label pairs to assign to this ManagedZone
        varType: map(any)
        defaultValue: {}
      - name: default_key_specs_key
        description: "Object containing default key signing specifications : algorithm, key_length, key_type, kind. Please see https://www.terraform.io/docs/providers/google/r/dns_managed_zone#dnssec_config for futhers details"
        varType: any
        defaultValue: {}
      - name: default_key_specs_zone
        description: "Object containing default zone signing specifications : algorithm, key_length, key_type, kind. Please see https://www.terraform.io/docs/providers/google/r/dns_managed_zone#dnssec_config for futhers details"
        varType: any
        defaultValue: {}
      - name: force_destroy
        description: Set this true to delete all records in the zone.
        varType: bool
        defaultValue: false
      - name: service_namespace_url
        description: The fully qualified or partial URL of the service directory namespace that should be associated with the zone. This should be formatted like https://servicedirectory.googleapis.com/v1/projects/{project}/locations/{location}/namespaces/{namespace_id} or simply projects/{project}/locations/{location}/namespaces/{namespace_id}.
        varType: string
        defaultValue: ""
      - name: recordsets
        description: List of DNS record objects to manage, in the standard terraform dns structure.
        varType: |-
          list(object({
              name    = string
              type    = string
              ttl     = number
              records = optional(list(string), null)

              routing_policy = optional(object({
                wrr = optional(list(object({
                  weight  = number
                  records = list(string)
                })), [])
                geo = optional(list(object({
                  location = string
                  records  = list(string)
                })), [])
              }))
            }))
        defaultValue: []
      - name: enable_logging
        description: Enable query logging for this ManagedZone
        varType: bool
        defaultValue: false
      - name: iam_choice
        description: Opt 1. iam_binding, 2. iam_member, 3. iam_policy
        varType: string
        required: true
      - name: member
        description: Identities that will be granted the privilege in role
        varType: string
        required: true
      - name: members
        description: Identities that will be granted the privilege in role
        varType: list(string)
        required: true
      - name: role
        description: The role that should be applied
        varType: string
        required: true
    outputs:
      - name: domain
        description: The DNS zone domain.
        type: string
      - name: etag
        description: The etag of the IAM policy
        type:
          - list
          - - string
      - name: name
        description: The DNS zone name.
        type: string
      - name: name_servers
        description: The DNS zone name servers.
        type:
          - list
          - - string
      - name: type
        description: The DNS zone type.
        type: string
  requirements:
    roles:
      - level: Project
        roles:
          - roles/iam.serviceAccountAdmin
          - roles/iam.serviceAccountUser
          - roles/resourcemanager.projectIamAdmin
          - roles/serviceusage.serviceUsageAdmin
          - roles/dns.admin
          - roles/compute.networkAdmin
          - roles/accesscontextmanager.policyAdmin
          - roles/iam.securityAdmin
    services:
      - dns.googleapis.com
      - compute.googleapis.com
      - cloudresourcemanager.googleapis.com
      - serviceusage.googleapis.com
    providerVersions:
      - source: hashicorp/google
        version: ">= 5.12.0, < 8"
      - source: hashicorp/google-beta
        version: ">= 5.12.0, < 8"
